---
title: "Python in R"
author: "Diya Bhat"
date: "12/11/2019"
output: html_document
---

One incredible advantage of using R-Markdown is its ability as a platform to be compatible with tons of languages apart from R such as: Python, SQL, Javascript, CSS, and more. R is a powerful tool, but sometimes the need arises to use a different language like Python, that is faster and contains packages that might not be available in R.
Here, we explore how to use Python on R-Markdown and an introduction to Python basics.

```{r setup, include=FALSE, echo = TRUE}
# To be able to use Python, we need to install the 'reticulate' package which makes Python and R interoperable
library(reticulate)
```

Functions are very useful because they save us time that would have otherwise been spent rewriting chunks of code over and over again.

```{python}
# this function takes in a string as its input and reverses it!
def reverse_string (word):
    result = ""
    for i in word :
         result = i + result
    return result      

# call the function
print("your string reversed looks like: ",reverse_string("the house was made of jellybeans"))

```
Regular expression (RegEx) is also handy when looking for specific patterns in large files as opposed to doing it manually. For example, given the very large string of letters and numbers below, if we wanted to extract only the urls, we could use re.findall() to specify what we are looking for it and return a list of all the matching subset strings

```{python}
# import the RegEx package 
import re

string = "<http://www.classmates.com/go/e/200988231/CC123101BT/CM00>  <http://graphics.classmates.com/graphics/spacer.gif>  <http://graphics.classmates.com/graphics/sp \
You have received this email because the requester specified you as their Manager. Please click http://itcapps.corp.enron.com/srrs/auth/emailLink.asp?ID=000000000053239&Page=Approval to review and act upon this request.     Request ID          : 000000000053239 Request Create Date\
ronOnline.   The following User ID and Password will give you access to live prices on the web-site http://www.enrononline.com.  User ID: ADM40601 Password: WELCOME!   (note these are case sensitive)    Please keep your User I\
<http://www.classmates.com/go/e/200988231/CC122401BC/CM00>  <http://graphics.classmates.com/graphics/spacer.gif>  <http://graphics.classmates.com/graphics/sp\
http://www.btinternet.com/~pir8/arnie/\
n, just click on the following hyperlink and complete the order form by Tuesday February 12, 2002.  http://zzz1.net/rd/rd.asp?ZXU=562&ZXD=1471085&UID=1471085  If you cannot link directly to the web site, simply cut and paste the address listed above into yo\
been successful getting in the group. To access the group should go to your web browser and type in http://www.egroups.com  The screen should show that you are a member of smu-betas group. When you replied to the original \
mber and password. For more details on how to log-on to eHRonline, see step-by-step instructions at http://isc.enron.com/site/doclibrary/user/ 2. Navigate to the pay advice using the following navigation menus: ? Pay Information ? Paycheck I\
In addition to World Markets Energy information  <http://esource.enron.com/worldmarket.asp> and Country Analysis and Forecasting, <http://esource.enron.com/worldmarket_CountryAnalysis.asp>  \
<http://ad.doubleclick.net/clk;3549492;6600300;c?http://www.sportingbetusa.com/english/casino/casinonew-fr.asp?isLogged=notlogged> A WEEKEND PAIR-A-DICE <http://ad.doubleclick.net/clk;3549492;6600300;c?http://www.sportingbetusa.c \
Mr. Skilling:  Your P number is P00500599.  For your convenience, you can also go to http://isc.enron.com/site/ under"


# match all strings beginning with 'http' and ending with a space
urls = re.findall(r"http.*?\s", string) 

# each element of the array can then be printed out on separate lines using a for loop
for i in urls:
  print(i)

```

